name = "ACEpsi"
uuid = "29a2b48e-e97a-4ce0-9095-f15688946fdc"
authors = ["Christoph Ortner <christohortner@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
